name: pythonic-misadventures
services:
  pythonic-misadventures:
    container_name: pythonic-misadventures
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "8080:80"


